feat(docs): document grouping chunks with Vite
vuejs/vue-router-next pull request #1178
Opened 2021-11-01 13:18 UTC by dpschen

2021-11-02 14:10 UTC, posva requested changes
Let's add a sub section

```md
### With webpack

...

### With Vite

...
```

2021-11-02 14:10 UTC, posva commented on docs/guide/advanced/lazy-loading.md
> +## Grouping Components in the Same Chunk with Webpack
```suggestion
## Grouping Components in the Same Chunk with webpack
```

2021-11-06 13:08 UTC, dpschen commented on docs/guide/advanced/lazy-loading.md
> +## Grouping Components in the Same Chunk with Webpack
Changed =)

2021-11-15 18:11 UTC, posva approved these changes
thanks!

2021-11-15 18:11 UTC, merged