refactor(matcher): add error message for v3 catchall
vuejs/vue-router-next pull request #506
Opened 2020-09-30 12:22 UTC by miyaoka

Got an error `Route "*" should be "/*".` when I set `path: '*'`.
However it still doesn't work (I didn't notice new catchall rule).

So added new error message for catchall.

2020-09-30 16:01 UTC, posva requested changes
Thank you but this should be a DEV only warning at the matcher level when adding a route that is **exactly** `'*'` because it doesn't start with a `/` so it's still fine to warn against it and it could help people migrating. Other paths like `/*` or `/path-*` are technically valid so they shouldn't warn

2020-09-30 20:45 UTC, miyaoka commented
`/*` is valid?

I got error `Route "*" should be "/*"`, so I changed `'*'` to `/*`. then got warn `[Vue Router warn]: No match found for location with path`. CatchAll doesn't work.

2020-10-01 06:59 UTC, posva commented
`/*` will match the `*` character, it no longer has a special meaning unless put after a param

2020-10-01 10:19 UTC, miyaoka commented
Ahhhh, I finally understand. Thank you.
I'll fix it to show warning instead of error.

2020-10-02 09:31 UTC, posva commented
I'm going to take over this one because I want to release a new version 🙂 
Thank you!

2020-10-02 09:44 UTC, miyaoka commented
OK! Thank you!

2020-10-02 09:49 UTC, posva commented
Merged at 14e1eb96485f74669f582a87f522d3b13b567c9c

I couldn't push to the branch, maybe you unticked the option on the right that allows maintainers to edit 🤔 I still kept you as the author though!

2020-10-02 09:49 UTC, closed without merging