docs: add a note for use functional component
vuejs/vue-router-next pull request #922
Opened 2021-05-05 07:33 UTC by PeterAlfredLee

Close #915

2021-05-05 08:34 UTC, posva requested changes
Thanks!

2021-05-05 08:34 UTC, posva commented on docs/api/index.md
> +const router = createRouter({ path: '/foo', component: Functional })
can you replace this with a `const routes = [{ ... }` like in the rest of the docs?

2021-05-05 08:34 UTC, posva commented on docs/api/index.md
> +const Functional = () => h('div', 'functional')
Something More contextual is better
```suggestion
const HomeView = () => h('div', 'HomePage')
```

2021-05-05 08:34 UTC, posva commented on docs/api/index.md
> +const router = createRouter({ path: '/foo', component: Functional })
Also having `/` instead of `/foo` would be better

2021-05-06 01:32 UTC, PeterAlfredLee commented
@posva Thank you for review this. Just pushed again. Please check it.

2021-05-06 02:16 UTC, edison1105 requested changes

2021-05-06 02:16 UTC, edison1105 commented on docs/zh/api/index.md
> +如果你想使用函数式组件, 请确保在组件上添加一个`displayName`。
```suggestion
如果你想使用函数式组件, 请确保在组件上添加一个 `displayName`。
```

2021-05-06 02:16 UTC, edison1105 commented on docs/zh/api/index.md
> +HomeView.displayName = 'HomeView'  // 在组件上添加一个`displayName`
```suggestion
HomeView.displayName = 'HomeView'  // 在组件上添加一个 `displayName`
```

2021-05-06 08:03 UTC, edison1105 approved these changes

2021-05-06 09:17 UTC, posva requested changes
Thanks! Can you adapt the last few changes on the Chinese doc as well, please?

2021-05-06 09:17 UTC, posva commented on docs/api/index.md
> +If you want to use a functional component, make sure to add a `displayName` to the component.
```suggestion
If you want to use a functional component, make sure to add a `displayName` to it.
```

2021-05-06 09:17 UTC, posva commented on docs/api/index.md
> +HomeView.displayName = 'HomeView'  // add a "displayName" to the component.
```suggestion
// in TypeScript, you will need to use the FunctionalComponent type
HomeView.displayName = 'HomeView'
```

2021-05-06 11:17 UTC, PeterAlfredLee commented on docs/api/index.md
> +If you want to use a functional component, make sure to add a `displayName` to the component.
ok

2021-05-06 11:17 UTC, PeterAlfredLee commented on docs/api/index.md
> +HomeView.displayName = 'HomeView'  // add a "displayName" to the component.
ok

2021-05-06 12:41 UTC, posva approved these changes
Thanks!

2021-05-06 12:42 UTC, merged