feat: support has # based url
vuejs/vue-router-next pull request #925
Opened 2021-05-06 08:28 UTC by GGwujun

2021-05-06 08:40 UTC, edison1105 commented
duplicate of this PR: #924

2021-05-06 08:46 UTC, GGwujun commented
See also [docs](https://developers.google.com/search/docs/ajax-crawling/docs/getting-started).

Fix #923

2021-05-06 09:21 UTC, posva requested changes
Thanks! Could you add a unit test to handle these bases

- `#!`
- `#other`

2021-05-10 08:26 UTC, posva requested changes
Thanks!

2021-05-10 08:26 UTC, posva commented on src/history/html5.ts
> +      hash.indexOf(base.slice(hashPos).toLowerCase()) > -1
```suggestion
      hash.includes(base.slice(hashPos))
```

2021-05-10 08:26 UTC, posva commented on src/history/html5.ts
> -    // prepend the starting slash to hash so the url starts with /#
can you add back the comment at line 50

2021-05-10 13:42 UTC, posva commented
I added tests that were failing before. They seem to be failing when ran with other tests but work when ran alone. It will need more investigation

2021-05-10 14:05 UTC, posva commented on src/history/html5.ts
> +
```suggestion
// prepend the starting slash to hash so the url starts with /#
```

2021-05-10 14:38 UTC, GGwujun commented on src/history/html5.ts
> +      hash.indexOf(base.slice(hashPos).toLowerCase()) > -1
good,thks

2021-05-13 08:03 UTC, posva approved these changes

2021-05-13 08:04 UTC, merged