Add VueSchool Summer Sale banner
vuejs/vue-router-next pull request #991
Opened 2021-06-08 02:49 UTC by nicodevs

This PR adds the Vue School banner, similar to the previous [PR 848](https://github.com/vuejs/vue-router-next/pull/848).

[Visuals can be seen here.](https://imgur.com/a/3Guio5g)

2021-06-08 06:58 UTC, posva commented
When should this be deployed?

2021-06-08 13:57 UTC, nicodevs commented
@posva, the landing page [is on production now](https://vueschool.io/sales/summer-vue/?friend=vuerouter) so you can merge this when you see fit :)

2021-06-08 20:16 UTC, posva requested changes

2021-06-08 20:16 UTC, posva commented on docs/.vitepress/theme/Layout.vue
> +import BannerTop from '../components/BannerTop.vue'
Can you make this async?

2021-06-09 14:46 UTC, nicodevs commented on docs/.vitepress/theme/Layout.vue
> +import BannerTop from '../components/BannerTop.vue'
Done! Let me know if it's OK @posva

2021-06-09 15:07 UTC, posva approved these changes
Thanks!

2021-06-09 15:07 UTC, merged